spring.application.name=airbnb-clone
server.port=${PORT:8080}

# Dynamic CORS Allowed Origins
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:*}

# H2 Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
